notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: tG7sZpmxUfd5BbpUdURARC8D93D+NcU2mZIvFejovi/eVh9SztL3VXV+mMDfB36ngI77TUezEEdQCf/PVvjR1ncIHXomQN531HxwdXjsG7kbDzTmkr7xmaWRwHYMt5ZFj60Rrgg7Cdcu5ZzbRTzIvAT1wGvgLLHFN8O/ARFuDwUuybMLt5DuNFOH4M4CxKdR0HXdCWEVrHBDR9tiYVYyjnE+OLlWeWywM63kN18GmyBRkzqwRlMygdN/mL6zmKFS0ayrT0Ohuv4rxaHBJ4ZgQWEQbfFMUcDwjFjYt/riEAR77SwxA15Kw7Tr5nsp5JFo3N2kQQ3jHAXT98WxY5b5zTsuLtOL7fz2nWtXluVsNkJCQ8Re4ebXG1v0MneMyALP17aOAyzB1tbICp8MZofRWRLLPmFM4ZiQbxB15ziLF71iVjzvdmxDDWPVgqsiHgF2nvUT9CXPPc4QhYOWE1+mvLGgvPAlGydz2FznNxkfjhyPWlWd7T/GYBCIe/PZSz26J05cfMLrWKvwZSVeRjKw1PuBTQkseziiDzgBzHNBWvKig4NY6+iv0OD53Qa6R6rso2myOevKjMAUPqYa81LQMzZs+2qMG+qBkBtngN/vFhifotENjlc8D/lKQKwU4opyl73Wap7mUY3IDleV8u7vXnv2S9SrT9iku1rZSnSqbLQ=
  api_key:
    secure: FPJEt6e3RuvujrC/vX40IXYlYTzYHIY5naQqtif6UkWAQxsnlolDIejdk6BlinG3o3M5E/DSEg4kJIXA01pTQQaD0am/zPbEXekgy07tBVhY7F3f5APCe7P+52ugVgXRa10nrn8uKWhZVN0tpvmoMbyoFQu+yQQY0uPXts8ENvFRsMqjQvDxzFKTUa+zFUydjOWzJDKlYeZHiOQh8wwWpykul5uPF+2hk/ztIsmcE/Y5w/1IS38ajqhMK8XkXzfz+pM2CmDhvCizSz+ZV4BM5zNIGMPvJZBm/PffGWg0DZJvI1hYr7aufgz43oenTWHilLt4nN/LWuiTy4WdEv9AAvXWU3NpDuEBSOlUOzacjPlMFWNIvrb16CT7uThIXM1cA1MnxYEyubkA3j/zXno+VgvmVlx90W4llmwMsYgNtkbpqVvn1LRNCaufOpp+j8xlx73Ewk2tl15BhbtR5/PKQ7MbgD8x70Sx5K56kePEjZif3RU+Y9/x76wHhAf3g4aRqbHwtayXWEgimjKXqp4RLwrIjyGKfccNxqy5jTCaHt0k+3bk4bK9vbzdiP4eggIEueen754mehRrCSiz2g0QDn6VshQ4ilfZ4fQe/NGQ/uk5PSTc6mdJB4Nj++EA1JBWPpeIeP1BwD23VzPW/QecHEuAd6hi3IDxrFBvHc9m61s=
  on:
    tags: true
