notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: tG7sZpmxUfd5BbpUdURARC8D93D+NcU2mZIvFejovi/eVh9SztL3VXV+mMDfB36ngI77TUezEEdQCf/PVvjR1ncIHXomQN531HxwdXjsG7kbDzTmkr7xmaWRwHYMt5ZFj60Rrgg7Cdcu5ZzbRTzIvAT1wGvgLLHFN8O/ARFuDwUuybMLt5DuNFOH4M4CxKdR0HXdCWEVrHBDR9tiYVYyjnE+OLlWeWywM63kN18GmyBRkzqwRlMygdN/mL6zmKFS0ayrT0Ohuv4rxaHBJ4ZgQWEQbfFMUcDwjFjYt/riEAR77SwxA15Kw7Tr5nsp5JFo3N2kQQ3jHAXT98WxY5b5zTsuLtOL7fz2nWtXluVsNkJCQ8Re4ebXG1v0MneMyALP17aOAyzB1tbICp8MZofRWRLLPmFM4ZiQbxB15ziLF71iVjzvdmxDDWPVgqsiHgF2nvUT9CXPPc4QhYOWE1+mvLGgvPAlGydz2FznNxkfjhyPWlWd7T/GYBCIe/PZSz26J05cfMLrWKvwZSVeRjKw1PuBTQkseziiDzgBzHNBWvKig4NY6+iv0OD53Qa6R6rso2myOevKjMAUPqYa81LQMzZs+2qMG+qBkBtngN/vFhifotENjlc8D/lKQKwU4opyl73Wap7mUY3IDleV8u7vXnv2S9SrT9iku1rZSnSqbLQ=
  api_key:
    secure: MuHiEIdZ4kKECxMOltkY9MiII0+JzOfn/HJ4VID3JBAu/VxOpS9eUNBs5qPeUDR4ACXjhKaoU1Xo6z0zM8A6Kb0DaI6ldv+MjHs5dDFUDVSxjL2i+HxL7pZOWQ0JUL22RAO44+mNoJqsuKvl2RwbKocRc8JKQtagPy4rdFOAcMzVvKv9xOx+CAOaIZGHzpDzL7offMLJhnUv3qGKoCAWAziVylFZmNg4GMiCLVc2QXXmXutHo92Jb1VleovQhgdehZR8MEpaeoSFPi2VX5oX/GW7RvwfqTJMuIasN1fuaAnAGZmHhf8+RCPqDXvxLp+iJZb5wHFXXL9qKB4+mOlTUo6/H9O5tsUYN42g3kykYMIXQ/2rieKHx+k2nTQQax9t+/JEVvkpITJJGGL58G+fGFpEyVpMd7mUvVGF5UHffhQnmsN2E1StQtQMrS6g8BNqpv26V8ShHqehZoVjvcOx5JLrES9FbNm5FG4dVmulmaKh6A3c9LUM64ez/4HhWLHGbRu8TUno5Rb3w03ecptzfqCfogx2azkHFDkowG0xesLt+dbOUZgmHtiJIcROY/EneoDooerTUjtK4ZWhFcUfq2AhywwE0xI9uAwMuu0cf7geZL2QfhQcokza5Xp+X9eD3FSyHaAq/wAQ8WRD0Za+Szg0EMwTcxcoPb+uYNzVIvY=
  on:
    tags: true
